apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: music-service
  annotations:
    kappnav.component.namespaces: ui-namespace, api-namespace
  labels:
    app: music-service
    solution: music-service
spec:
  componentKinds:
  - group: core
    kind: Pod
  - group: core
    kind: Deployment
  - group: core
    kind: Service
  - group: openshift.io
    kind: Route
  selector:
    matchLabels:
      solution: music-service